import type { ActivityKind, ActivityStatus } from '@lpg/types'

/**
 * Mirror of the `activity_statuses` database table seed.
 * Used for unit tests, offline development, and fake adapter fallback.
 */
export const ACTIVITY_STATUS_DEFAULTS: ActivityStatus[] = [
  // ── 8 Statuts Tournées (TOUR) ──────────────────────────────────
  {
    activity: 'TOUR',
    status_value: 'DRAFT',
    code: 'BRN',
    label: 'Brouillon',
    description: 'Tournée en cours de préparation, non encore transmise.',
    tone: 'slate',
    sort_order: 1,
    is_active: true,
  },
  {
    activity: 'TOUR',
    status_value: 'PLANNED',
    code: 'PLN',
    label: 'Planifiée',
    description: 'Tournée planifiée et validée, prête pour le chargement au dépôt.',
    tone: 'sky',
    sort_order: 2,
    is_active: true,
  },
  {
    activity: 'TOUR',
    status_value: 'PENDINGTRANSPORTERACK',
    code: 'ATT',
    label: 'En attente accusé transporteur',
    description: 'Tournée externalisée transmise au transporteur, en attente d’affectation de l’équipage.',
    tone: 'amber',
    sort_order: 3,
    is_active: true,
  },
  {
    activity: 'TOUR',
    status_value: 'ACKNOWLEDGED',
    code: 'ACC',
    label: 'Accusé de réception validé',
    description: 'Tournée acceptée par le transporteur avec véhicule, chauffeur et convoyeur assignés.',
    tone: 'blue',
    sort_order: 4,
    is_active: true,
  },
  {
    activity: 'TOUR',
    status_value: 'INPROGRESS',
    code: 'CRS',
    label: 'En transit / En cours',
    description: 'Cargaison chargée au dépôt, camion en rotation vers les sites clients.',
    tone: 'emerald',
    sort_order: 5,
    is_active: true,
  },
  {
    activity: 'TOUR',
    status_value: 'COMPLETED',
    code: 'TRM',
    label: 'Livrée / Clôturée',
    description: 'Toutes les livraisons clients ont été effectuées et attestées par preuve de dépotage.',
    tone: 'emerald',
    sort_order: 6,
    is_active: true,
  },
  {
    activity: 'TOUR',
    status_value: 'CANCELLED',
    code: 'ANN',
    label: 'Annulée',
    description: 'Tournée annulée avant chargement de la cargaison.',
    tone: 'rose',
    sort_order: 7,
    is_active: true,
  },
  {
    activity: 'TOUR',
    status_value: 'INCIDENT',
    code: 'INC',
    label: 'Incident / Litige',
    description: 'Anomalie ou écart de cargaison majeur constaté pendant la tournée.',
    tone: 'rose',
    sort_order: 8,
    is_active: true,
  },

  // ── 5 Statuts Enlèvements (PICKUP) ─────────────────────────────────
  {
    activity: 'PICKUP',
    status_value: 'DRAFT',
    code: 'BRN',
    label: 'Brouillon',
    description: 'Demande d’enlèvement en cours de saisie.',
    tone: 'slate',
    sort_order: 1,
    is_active: true,
  },
  {
    activity: 'PICKUP',
    status_value: 'VALIDATED',
    code: 'VAL',
    label: 'Planifié / Validé',
    description: 'Enlèvement validé sur quota au dépôt amont (SCDP/SNH).',
    tone: 'sky',
    sort_order: 2,
    is_active: true,
  },
  {
    activity: 'PICKUP',
    status_value: 'INPROGRESS',
    code: 'CRS',
    label: 'En cours de chargement',
    description: 'Camion présent au dépôt source pour chargement et pesée.',
    tone: 'amber',
    sort_order: 3,
    is_active: true,
  },
  {
    activity: 'PICKUP',
    status_value: 'COMPLETED',
    code: 'TRM',
    label: 'Enlevé & Scellé',
    description: 'Chargement achevé, scellés vérifiés et bon d’enlèvement émis.',
    tone: 'emerald',
    sort_order: 4,
    is_active: true,
  },
  {
    activity: 'PICKUP',
    status_value: 'CANCELLED',
    code: 'ANN',
    label: 'Annulé',
    description: 'Demande d’enlèvement annulée.',
    tone: 'rose',
    sort_order: 5,
    is_active: true,
  },

  // ── 4 Statuts Checkpoints (CHECKPOINT) ────────────────────────────
  {
    activity: 'CHECKPOINT',
    status_value: 'PENDING',
    code: 'ATT',
    label: 'En attente',
    description: 'Étape en attente d’exécution.',
    tone: 'slate',
    sort_order: 1,
    is_active: true,
  },
  {
    activity: 'CHECKPOINT',
    status_value: 'INPROGRESS',
    code: 'CRS',
    label: 'En cours',
    description: 'Camion sur site pour opération de contrôle, chargement ou dépotage.',
    tone: 'amber',
    sort_order: 2,
    is_active: true,
  },
  {
    activity: 'CHECKPOINT',
    status_value: 'COMPLETED',
    code: 'VAL',
    label: 'Validé / Dépoté',
    description: 'Pesée, livraison ou passage validé avec justificatif horodaté.',
    tone: 'emerald',
    sort_order: 3,
    is_active: true,
  },
  {
    activity: 'CHECKPOINT',
    status_value: 'SKIPPED',
    code: 'IGN',
    label: 'Contourné / Ignoré',
    description: 'Étape non exécutée lors du trajet.',
    tone: 'rose',
    sort_order: 4,
    is_active: true,
  },

  // ── 7 Statuts Contrats (CONTRACT) ─────────────────────────────────
  {
    activity: 'CONTRACT',
    status_value: 'PENDING',
    code: 'ATT',
    label: 'En attente validation',
    description: 'Contrat déclaré en attente d’instruction initiale.',
    tone: 'amber',
    sort_order: 1,
    is_active: true,
  },
  {
    activity: 'CONTRACT',
    status_value: 'PENDINGTRANSPORTERACK',
    code: 'ACK',
    label: 'En attente acceptation transporteur',
    description: 'Contrat transmis au transporteur pour signature et acceptation.',
    tone: 'amber',
    sort_order: 2,
    is_active: true,
  },
  {
    activity: 'CONTRACT',
    status_value: 'ACTIVE',
    code: 'ACT',
    label: 'Actif',
    description: 'Contrat en vigueur, éligible pour l’externalisation des tournées.',
    tone: 'emerald',
    sort_order: 3,
    is_active: true,
  },
  {
    activity: 'CONTRACT',
    status_value: 'UPCOMING',
    code: 'AVN',
    label: 'À venir',
    description: 'Contrat validé dont la date de début est future.',
    tone: 'sky',
    sort_order: 4,
    is_active: true,
  },
  {
    activity: 'CONTRACT',
    status_value: 'EXPIRED',
    code: 'EXP',
    label: 'Expiré',
    description: 'Contrat dont la date d’échéance est dépassée.',
    tone: 'slate',
    sort_order: 5,
    is_active: true,
  },
  {
    activity: 'CONTRACT',
    status_value: 'SUSPENDED',
    code: 'SUS',
    label: 'Suspendu',
    description: 'Contrat temporairement gelé pour motif administratif ou réglementaire.',
    tone: 'rose',
    sort_order: 6,
    is_active: true,
  },
  {
    activity: 'CONTRACT',
    status_value: 'CANCELLED',
    code: 'RES',
    label: 'Résilié',
    description: 'Contrat rompu ou annulé de façon définitive.',
    tone: 'rose',
    sort_order: 7,
    is_active: true,
  },
]

/**
 * Quick synchronous helper to find status metadata from defaults.
 */
export function resolveDefaultActivityStatus(
  activity: ActivityKind,
  statusValue: string,
): ActivityStatus | undefined {
  return ACTIVITY_STATUS_DEFAULTS.find(
    (item) => item.activity === activity && item.status_value === statusValue,
  )
}
